### ISSUE TITLE
Configurable Breakpoints

### ISSUE THREAD

**Issue by AaronNBrock** [zerodevx/svelte-img#14]
For images which only cover a small portion of the view port, it would be useful to be able to define breakpoints as opposed to the breakpoints always the width of the rendered image [on this line](https://github.com/zerodevx/svelte-img/blob/67a6d6e43b76da7ae5e41a700fa479e797e4204f/src/lib/SvelteImg.svelte#L38).

I'm happy to help contribute, but I'm not sure the best way to implement this.  It could be as simple as adding an exported field on the `SvelteImg` component:

```svelte
<SvelteImg src={MyImg} breakpoints=[480, 720, 1080] /> 
```

or adding as an import option:

```svelte
import testBasic from '../cat01.jpg?breakpoints=480;720;1080&run'
```
or something else, would love your thoughts @zerodevx 

I'm happy to help contribute, but I'm not sure the best way to implement this.

**Comment by zerodevx** [comment]
Hey, apologies for the late reply. Stoked that you're able to help! I'm also wondering what the best way to handle this is. I'm bit apprehensive for `svelte-img` to handle [art direction](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#art_direction) - kinda think it should focus on solving the most common cases.

**Comment by AaronNBrock** [comment]
Thanks for the art direction link ~ I hadn't even thought of that!

In my use case I'm not trying to change the variants that are generated but when they are displayed.  Specifically I have an image which only takes up about 10% the width of the page, but at the moment by default when the screen is 1920px wide svelte-img will display the image with 1920w even though the image is only 1/10th that width.  I'd like to be able to configure that.

**Comment by zerodevx** [comment]
So the recommended way is to use the `sizes` attribute as described [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes). I'll add an example into the docs.

**Comment by zerodevx** [comment]
This has been added to the [docs](https://github.com/zerodevx/svelte-img#art-direction).
