### ISSUE TITLE
Doubled "class" attribute in Blurred image placeholders

### ISSUE THREAD

**Issue by nomideusz** [zerodevx/svelte-img#32]
It seems there is an error in the "Blurred image placeholders" docs section. The "class" attribute is used twice here:

<Img **class="better-blur" class={loaded}** on:load={() => (loaded = true)} {src} alt="cat" />.

**Comment by zerodevx** [comment]
Thanks, fixed by https://github.com/zerodevx/svelte-img/commit/de029f83fbb3008fb205a120f1b2b1ad25b793df. Good catch!
