### ISSUE TITLE
Image cache

### ISSUE THREAD

**Issue by Suyashtnt** [zerodevx/svelte-img#35]
It would be really nice if it could cache pre-built images in .svelte-kit or similar so the image cache can be shared across builds/CI

**Comment by zerodevx** [comment]
This should probably be solved at the `vite` or `vite-imagetools` level. There's ongoing discussion [here](https://github.com/JonasKruckenberg/imagetools/issues/522).

**Comment by benmccann** [comment]
The latest version of `vite-imagetools` now includes a cache

**Comment by Suyashtnt** [comment]
well then

**Comment by zerodevx** [comment]
> The latest version of `vite-imagetools` now includes a cache

@benmccann Thanks for the heads-up, I'll check it out.

**Comment by benmccann** [comment]
`@sveltejs/enhanced-img` also uses `vite-imagetools`, so it now supports caching as well
