### ISSUE TITLE
Any plans for Svelte 5 support?

### ISSUE THREAD

**Issue by westernwontons** [zerodevx/svelte-img#50]

**Comment by zerodevx** [comment]
Yes. Will get to it once I have a moment.

**Comment by westernwontons** [comment]
I would be happy to help!

**Comment by zerodevx** [comment]
Happy to take your PR!

**Comment by zerodevx** [comment]
Svelte 5 is allowed from `v2.1.1` since it's (supposedly) backward compatible; will leave #51 to track pure `v5` migration when the stable lands. Thanks for your help!
